In [43]:
import pandas as pd
import openpyxl

In [44]:
path = r"H:\3ª ETAPA\Python\projetos-python\aula4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [45]:
tabela = pd.read_excel(path, header=2)

In [46]:
print(tabela.columns)

Index(['Unnamed: 0', 'UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022'],
      dtype='str')

In [47]:
tabela

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
col_2010 = 'População 2010 (Alterações de Limites até 2022)1'
col_2022 = 'População Censo 2022'

pop_estado = (
    tabela.groupby(["COD. UF", "UF"], as_index=False)
      .agg(
          populacao_2010=(col_2010, "sum"),
          populacao_2022=(col_2022, "sum"),
      )
)

pop_estado["crescimento"] = pop_estado["populacao_2022"] - pop_estado["populacao_2010"]
pop_estado = pop_estado.sort_values("crescimento", ascending=False).reset_index(drop=True)
pop_estado

    COD. UF  UF  populacao_2010  populacao_2022  crescimento
0      35.0  SP      41262199.0      44411238.0    3149039.0
1      42.0  SC       6248436.0       7610361.0    1361925.0
2      52.0  GO       6001789.0       7056495.0    1054706.0
3      41.0  PR      10444526.0      11444380.0     999854.0
4      31.0  MG      19597330.0      20539989.0     942659.0
5      51.0  MT       3035122.0       3658649.0     623527.0
6      15.0  PA       7581051.0       8120131.0     539080.0
7      13.0  AM       3483985.0       3941613.0     457628.0
8      23.0  CE       8451644.0       8794957.0     343313.0
9      32.0  ES       3514952.0       3833712.0     318760.0
10     50.0  MS       2449024.0       2757013.0     307989.0
11     26.0  PE       8796055.0       9058931.0     262876.0
12     53.0  DF       2572159.0       2817381.0     245222.0
13     25.0  PB       3766528.0       3974687.0     208159.0
14     21.0  MA       6574789.0       6776699.0     201910.0
15     43.0  RS      10693929.0      10882965.0     189036.0
16     14.0  RR        450479.0        636707.0     186228.0
17     22.0  PI       3119097.0       3271199.0     152102.0
18     28.0  SE       2067852.0       2210004.0     142152.0
19     24.0  RN       3168027.0       3302729.0     134702.0
20     17.0  TO       1383445.0       1511460.0     128015.0
21     29.0  BA      14017071.0      14141626.0     124555.0
22     12.0  AC        733559.0        830018.0      96459.0
23     33.0  RJ      15989929.0      16055174.0      65245.0
24     16.0  AP        669526.0        733759.0      64233.0
25     11.0  RO       1562409.0       1581196.0      18787.0
26     27.0  AL       3120887.0       3127683.0       6796.0

In [49]:
pop_estado.to_csv("populacao_por_estado.csv", index=False)

In [50]:
pop_municipio = tabela[["COD. UF", "UF", "COD. MUNIC", "NOME DO MUNICÍPIO", col_2010, col_2022]].copy()
pop_municipio = pop_municipio.rename(columns={col_2010: "populacao_2010", col_2022: "populacao_2022"})

pop_municipio["crescimento"] = pop_municipio["populacao_2022"] - pop_municipio["populacao_2010"]
pop_municipio = pop_municipio.sort_values("crescimento", ascending=False).reset_index(drop=True)
pop_municipio

,COD. UF,UF,COD. MUNIC,NOME DO MUNICÍPIO,populacao_2010,populacao_2022,crescimento
0,13.0,AM,2603.0,Manaus,1802014.0,2063689.0,261675.0
1,53.0,DF,108.0,Brasília,2572159.0,2817381.0,245222.0
2,35.0,SP,50308.0,São Paulo,11253503.0,11451999.0,198496.0
3,35.0,SP,52205.0,Sorocaba,586816.0,723682.0,136866.0
4,52.0,GO,8707.0,Goiânia,1301912.0,1437366.0,135454.0
...,...,...,...,...,...,...,...
5569,29.0,BA,27408.0,Salvador,2675656.0,2417678.0,-257978.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN

In [51]:
pop_municipio.to_csv("populacao_por_municipio.csv", index=False)